### PR TITLE
Does not work if DNN is running as a virtual directory

### PR DESCRIPTION
**Pull request by vmasanas**
Fix for https://github.com/DNN-Connect/IdentitySwitcher/issues/47

### CODE REVIEW

**Comment by serge-van-der-ven** [comment]
Hi Vicenç, Ernst Peter asked me to review your PR. Thanks for picking this up! Your solution with appPath is OK, however it could (should) be implemented a bit cleaner.

1. Instead of adding appPath everywhere (in the Angular code), just add an AppPath property in the file ModuleInstanceBase. You'll only need a get (readonly) property in the ModuleInstanceBase.cs if you initialize this with the DNN Application Path (DotNetNuke.Common.Globals.ApplicationPath). If you wish you can add [JsonProperty("appPath")] to this property to have it camelCase in the javascript.
2. In the identitySwitcher.d.ts file, add the property to the IModuleInstance. Note: if you used [JsonProperty("appPath")], the property should be appPath: string, otherwise AppPath: string.
3. Finally in the identitySwitcherFactory.ts remove your appPath argument and replace in all methods const apiUrl: string = appPath +.... with const apiUrl =moduleInstance.AppPath + this.config.apiUrl (again if you forced camelCase, this should be moduleInstance.appPath

In the end, you should have a minimum number of changes. In the backend, just adding a property. In the TypeScript extending an interface w/ a property and using this property in the API calls in the factory

**Comment by vmasanas** [comment]
Serge, thanks for the review but I'm not familiar with Angular since we mainly use React here. Would you implement the changes or should I do this and resend the PR?

**Comment by serge-van-der-ven** [comment]
No prob. I will fix this for you!

**Comment by serge-van-der-ven** [comment]
@EPTamminga - This PR can be replaced by PR #50.

**Comment by EPTamminga** [comment]
Replaced by PR #50

**Pull request closed without merging**
